export const PRODUCT_EMOJIS_EPICERIE = [
  // RIZ
  { emoji: '🍚', label: 'Riz' },
  { emoji: '🍚', label: 'Riz brisé' },
  { emoji: '🍚', label: 'Riz parfumé' },
  { emoji: '🍚', label: 'Riz entier' },

  // CÉRÉALES, FARINES ET FÉCULENTS
  { emoji: '🌾', label: 'Mil' },
  { emoji: '🌽', label: 'Maïs' },
  { emoji: '🌾', label: 'Sorgho' },
  { emoji: '🌾', label: 'Fonio' },
  { emoji: '🍝', label: 'Couscous' },
  { emoji: '🍝', label: 'Semoule' },
  { emoji: '🥄', label: 'Farine' },
  { emoji: '🍝', label: 'Vermicelles' },
  { emoji: '🍝', label: 'Pâtes' },
  { emoji: '🍜', label: 'Nouilles' },

  // LÉGUMINEUSES
  { emoji: '🫘', label: 'Niébé' },
  { emoji: '🫘', label: 'Haricots' },
  { emoji: '🫘', label: 'Lentilles' },
  { emoji: '🫘', label: 'Pois' },
  { emoji: '🫘', label: 'Pois chiches' },
  { emoji: '🫘', label: 'Soja' },
  { emoji: '🥜', label: 'Arachides' },

  // HUILES ET MATIÈRES GRASSES
  { emoji: '🍶', label: 'Huile de palme' },
  { emoji: '🫒', label: 'Huile d\'arachide' },
  { emoji: '🫒', label: 'Huile de soja' },
  { emoji: '🫒', label: 'Huile végétale' },
  { emoji: '🫒', label: 'Huile de tournesol' },
  { emoji: '🫒', label: 'Huile d\'olive' },
  { emoji: '🧈', label: 'Margarine' },
  { emoji: '🧈', label: 'Beurre' },

  // SEL, SUCRE ET ASSAISONNEMENTS
  { emoji: '🍯', label: 'Sucre' },
  { emoji: '🧂', label: 'Sel' },
  { emoji: '🥘', label: 'Bouillon cube' },
  { emoji: '🧂', label: 'Poivre' },
  { emoji: '🌶️', label: 'Piment' },
  { emoji: '🌶️', label: 'Piment poudre' },
  { emoji: '🧂', label: 'Paprika' },
  { emoji: '🧂', label: 'Curry' },
  { emoji: '🧂', label: 'Gingembre' },
  { emoji: '🧄', label: 'Ail poudre' },
  { emoji: '🧂', label: 'Épices' },

  // CONSERVES ET SAUCES
  { emoji: '🍅', label: 'Concentré tomate' },
  { emoji: '🍅', label: 'Tomates pelées' },
  { emoji: '🥫', label: 'Sauce' },
  { emoji: '🍯', label: 'Mayonnaise' },
  { emoji: '🥒', label: 'Moutarde' },
  { emoji: '🍅', label: 'Ketchup' },
  { emoji: '🌶️', label: 'Sauce piment' },
  { emoji: '🍶', label: 'Sauce soja' },
  { emoji: '🐟', label: 'Sardines' },
  { emoji: '🐟', label: 'Thon' },
  { emoji: '🐟', label: 'Maquereau' },
  { emoji: '🥫', label: 'Corned-beef' },
  { emoji: '🫘', label: 'Haricots conserve' },
  { emoji: '🥬', label: 'Petits pois' },
  { emoji: '🥛', label: 'Lait concentré' },

  // LAIT ET PETIT-DÉJEUNER
  { emoji: '🥛', label: 'Lait poudre' },
  { emoji: '🥛', label: 'Lait UHT' },
  { emoji: '☕', label: 'Café soluble' },
  { emoji: '☕', label: 'Café moulu' },
  { emoji: '🍵', label: 'Thé' },
  { emoji: '🍫', label: 'Chocolat poudre' },
  { emoji: '🥣', label: 'Céréales' },
  { emoji: '🥣', label: 'Flocons avoine' },
  { emoji: '🍯', label: 'Confiture' },
  { emoji: '🍯', label: 'Miel' },
  { emoji: '🍫', label: 'Pâte tartiner' },
  { emoji: '🍞', label: 'Biscottes' },
  { emoji: '🍞', label: 'Pain de mie' },

  // BOISSONS
  { emoji: '💧', label: 'Eau' },
  { emoji: '🧃', label: 'Jus Bissap' },
  { emoji: '🧃', label: 'Jus Bouye' },
  { emoji: '🧃', label: 'Jus Gingembre' },
  { emoji: '🧃', label: 'Jus Tamarin' },
  { emoji: '🧃', label: 'Jus fruits' },
  { emoji: '🥤', label: 'Soda' },
  { emoji: '🥤', label: 'Boisson énergisante' },
  { emoji: '🥛', label: 'Boisson maltée' },
  { emoji: '🧋', label: 'Thé glacé' },

  // BISCUITS ET CONFISERIES
  { emoji: '🍪', label: 'Biscuits' },
  { emoji: '🍪', label: 'Crackers' },
  { emoji: '🍯', label: 'Madeleines' },
  { emoji: '🍬', label: 'Bonbons' },
  { emoji: '🍭', label: 'Chewing-gums' },
  { emoji: '🍭', label: 'Sucettes' },
  { emoji: '🍫', label: 'Chocolats' },
  { emoji: '🍫', label: 'Barres chocolatées' },
  { emoji: '🥔', label: 'Chips' },
  { emoji: '🥜', label: 'Cacahuètes grillées' },
  { emoji: '🥜', label: 'Noix cajou' },

  // PRODUITS DE BOULANGERIE
  { emoji: '🍞', label: 'Pain baguette' },
  { emoji: '🍞', label: 'Pain de mie' },
  { emoji: '🥐', label: 'Croissants' },
  { emoji: '🥐', label: 'Brioches' },

  // PRODUITS MÉNAGERS
  { emoji: '🧼', label: 'Savon ménage' },
  { emoji: '🧼', label: 'Savon liquide' },
  { emoji: '👕', label: 'Lessive poudre' },
  { emoji: '👕', label: 'Lessive liquide' },
  { emoji: '🚰', label: 'Eau Javel' },
  { emoji: '🧹', label: 'Nettoyant sol' },
  { emoji: '🧹', label: 'Nettoyant' },
  { emoji: '🥄', label: 'Liquide vaisselle' },
  { emoji: '🧽', label: 'Éponge' },
  { emoji: '🧹', label: 'Récurage' },
  { emoji: '💨', label: 'Désodorisant' },
  { emoji: '🐛', label: 'Insecticide' },
  { emoji: '📄', label: 'Film alimentaire' },
  { emoji: '🗑️', label: 'Sacs poubelle' },

  // HYGIÈNE CORPORELLE
  { emoji: '🧼', label: 'Savon toilette' },
  { emoji: '🚿', label: 'Gel douche' },
  { emoji: '💆', label: 'Shampooing' },
  { emoji: '💆', label: 'Après-shampooing' },
  { emoji: '🦷', label: 'Dentifrice' },
  { emoji: '🪥', label: 'Brosse dents' },
  { emoji: '💨', label: 'Déodorant' },
  { emoji: '🧴', label: 'Crème corporelle' },
  { emoji: '🧴', label: 'Vaseline' },
  { emoji: '🧴', label: 'Huile corporelle' },
  { emoji: '🧻', label: 'Papier toilette' },
  { emoji: '🧻', label: 'Mouchoirs' },
  { emoji: '👶', label: 'Serviettes hygiéniques' },
  { emoji: '🧻', label: 'Coton' },
  { emoji: '🧻', label: 'Coton-tiges' },

  // PRODUITS BÉBÉ
  { emoji: '🥛', label: 'Lait infantile' },
  { emoji: '🥣', label: 'Céréales bébé' },
  { emoji: '🧷', label: 'Couches' },
  { emoji: '🧷', label: 'Lingettes' },
  { emoji: '🧼', label: 'Savon bébé' },
  { emoji: '💆', label: 'Shampooing bébé' },
  { emoji: '👶', label: 'Crème bébé' },

  // ŒUFS
  { emoji: '🥚', label: 'Œufs' },

  // PRODUITS TYPIQUEMENT SÉNÉGALAIS
  { emoji: '🥜', label: 'Arachide grillée' },
  { emoji: '🥜', label: 'Arachide décortiquée' },
  { emoji: '🥜', label: 'Pâte arachide' },
  { emoji: '🧃', label: 'Bouye' },
  { emoji: '🧃', label: 'Bissap' },
  { emoji: '🧄', label: 'Gingembre frais' },
  { emoji: '🧃', label: 'Tamarin' },
  { emoji: '🌾', label: 'Nébeday' },
  { emoji: '🥘', label: 'Soumbala' },
  { emoji: '☕', label: 'Café Touba' },
  { emoji: '🍚', label: 'Thiéré' },
  { emoji: '🐟', label: 'Poisson séché' },
  { emoji: '🐟', label: 'Guedj' },
  { emoji: '🐟', label: 'Yet' },
  { emoji: '🦐', label: 'Crevettes séchées' },
  { emoji: '🌶️', label: 'Piment séché' },

  // GÉNÉRAL
  { emoji: '📦', label: 'Produit' },
  { emoji: '⚙️', label: 'Autre' },
]
