export const PRODUCT_EMOJIS = [
  { emoji: '🍕', label: 'Pizza' },
  { emoji: '🍔', label: 'Hamburger' },
  { emoji: '🍟', label: 'Frites' },
  { emoji: '🌭', label: 'Hot Dog' },
  { emoji: '🥗', label: 'Salade' },
  { emoji: '🍝', label: 'Pâtes' },
  { emoji: '🍜', label: 'Nouilles' },
  { emoji: '🍲', label: 'Soupe' },
  { emoji: '🥘', label: 'Ragoût' },
  { emoji: '🍛', label: 'Curry' },
  { emoji: '🍱', label: 'Bento' },
  { emoji: '🍣', label: 'Sushi' },
  { emoji: '🍤', label: 'Crevettes' },
  { emoji: '🥩', label: 'Viande' },
  { emoji: '🍗', label: 'Poulet' },
  { emoji: '🥓', label: 'Bacon' },
  { emoji: '🧀', label: 'Fromage' },
  { emoji: '🥕', label: 'Carotte' },
  { emoji: '🥔', label: 'Pomme de terre' },
  { emoji: '🌽', label: 'Maïs' },
  { emoji: '🥒', label: 'Concombre' },
  { emoji: '🥬', label: 'Légume' },
  { emoji: '🍅', label: 'Tomate' },
  { emoji: '🍆', label: 'Aubergine' },
  { emoji: '🥑', label: 'Avocat' },
  { emoji: '🍎', label: 'Pomme' },
  { emoji: '🍊', label: 'Orange' },
  { emoji: '🍌', label: 'Banane' },
  { emoji: '🍋', label: 'Citron' },
  { emoji: '🍉', label: 'Pastèque' },
  { emoji: '🍇', label: 'Raisin' },
  { emoji: '🍓', label: 'Fraise' },
  { emoji: '🫐', label: 'Myrtille' },
  { emoji: '🥝', label: 'Kiwi' },
  { emoji: '🍑', label: 'Pêche' },
  { emoji: '🍒', label: 'Cerise' },
  { emoji: '🍞', label: 'Pain' },
  { emoji: '🥐', label: 'Croissant' },
  { emoji: '🥨', label: 'Bretzel' },
  { emoji: '🥯', label: 'Bagel' },
  { emoji: '🧈', label: 'Beurre' },
  { emoji: '🥖', label: 'Baguette' },
  { emoji: '🍰', label: 'Gâteau' },
  { emoji: '🎂', label: 'Gâteau d\'anniversaire' },
  { emoji: '🧁', label: 'Cupcake' },
  { emoji: '🍪', label: 'Cookie' },
  { emoji: '🍩', label: 'Donut' },
  { emoji: '🍫', label: 'Chocolat' },
  { emoji: '🍬', label: 'Bonbon' },
  { emoji: '🍭', label: 'Sucette' },
  { emoji: '☕', label: 'Café' },
  { emoji: '🍵', label: 'Thé' },
  { emoji: '🥤', label: 'Verre' },
  { emoji: '🧃', label: 'Jus' },
  { emoji: '🧋', label: 'Bubble tea' },
  { emoji: '🍶', label: 'Sake' },
  { emoji: '🍺', label: 'Bière' },
  { emoji: '🍻', label: 'Bière (verre)' },
  { emoji: '🥂', label: 'Champagne' },
  { emoji: '🍷', label: 'Vin' },
  { emoji: '🥃', label: 'Bol' },
  { emoji: '⚙️', label: 'Autre' },
  { emoji: '📦', label: 'Produit' },
  { emoji: '🛍️', label: 'Achat' },
  { emoji: '💼', label: 'Affaires' },
  { emoji: '👕', label: 'Vêtement' },
  { emoji: '👔', label: 'Costume' },
  { emoji: '👗', label: 'Robe' },
  { emoji: '👠', label: 'Chaussure' },
  { emoji: '👜', label: 'Sac' },
  { emoji: '⌚', label: 'Montre' },
  { emoji: '💍', label: 'Bijou' },
  { emoji: '🧴', label: 'Produit ménager' },
  { emoji: '🧼', label: 'Savon' },
  { emoji: '🧽', label: 'Éponge' },
  { emoji: '🧹', label: 'Balai' },
  { emoji: '🧺', label: 'Panier' },
  { emoji: '📚', label: 'Livre' },
  { emoji: '✏️', label: 'Fourniture' },
  { emoji: '🖊️', label: 'Stylo' },
  { emoji: '📝', label: 'Document' },
  { emoji: '💻', label: 'Ordinateur' },
  { emoji: '📱', label: 'Téléphone' },
  { emoji: '⚽', label: 'Sport' },
  { emoji: '🎮', label: 'Jeu vidéo' },
  { emoji: '🎨', label: 'Art' },
  { emoji: '🎭', label: 'Théâtre' },
  { emoji: '🎵', label: 'Musique' },
  { emoji: '🎬', label: 'Film' },
  { emoji: '🌟', label: 'Spécial' },
]
