export const Icons = {
  cashier: '💳',
  sales: '📋',
  products: '📦',
  clients: '👥',
  credits: '📖',
  dashboard: '📊',
  calculator: '🔢',
  scanner: '📱',
  chevronLeft: '❮',
  chevronRight: '❯',
  close: '✕',
  minus: '−',
  plus: '+',
  delete: '🗑️',
  logout: '🚪',
}
